language: node_js
node_js:
  - "8"

warnings_are_errors: false

services: mongodb

before_script:
  - export NODE_ENV=test
  - sleep 15
  - mongo mongoStratus --eval 'db.accounts.insert({username: "admin",databases: [{ip: "localhost",port: 27017}]});'

scripts:
  - npm run lint
  - npm run test-unit
  - npm run test-integration
