language: node_js
node_js:
  - "8"

warnings_are_errors: false

services: mongodb

env:
  - NODE_ENV=test

before_script:
  - sleep 15

script:
  - npm run lint
  - npm run test-unit
  - npm run test-integration
