language: node_js
node_js:
  - "8"

warnings_are_errors: false

services: mongodb

env:
  - NODE_ENV=dev

before_script:
  - mongo mongoStratus --eval 'db.accounts.insert({username:"admin",token:"z321",databases:[{serverName:"mongoStratus",ip:"localhost",port:27017}]});'

script:
  - npm test
